services:
  nginx_ft_onion:
    # profiles: ["dev"]
    # depends_on:
    #   - frontend-dev
    build:
      dockerfile: ./nginx/Dockerfile
    volumes:
    - ./html:/usr/share/nginx/html
    ports:
      # - "8443:443"
      - "8080:80"
